# Generated by Django 4.0.7 on 2022-09-16 13:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultSMSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_name', models.CharField(max_length=200)),
                ('operator_prefix', models.CharField(max_length=200)),
                ('masking_sms_rate', models.FloatField(default=0)),
                ('non_masking_sms_rate', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Default SMS Rate',
                'verbose_name_plural': 'Default SMS Rate',
            },
        ),
        migrations.CreateModel(
            name='SenderID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=13, unique=True)),
                ('default', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sender ID',
                'verbose_name_plural': 'Sender ID',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('address', models.TextField()),
                ('config_status', models.BooleanField(blank=True, default=False, null=True)),
                ('credit', models.FloatField(blank=True, default=0, null=True)),
                ('expiry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user_image', models.URLField(blank=True, default='defaults/user.png', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Info',
                'verbose_name_plural': 'User Info',
            },
        ),
        migrations.AddIndex(
            model_name='senderid',
            index=models.Index(fields=['sender_id'], name='nf_core_sen_sender__e60d6e_idx'),
        ),
        migrations.AddIndex(
            model_name='defaultsmsrate',
            index=models.Index(fields=['operator_name', 'operator_prefix'], name='nf_core_def_operato_e9e322_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['user', 'mobile'], name='nf_core_use_user_id_ff0f6f_idx'),
        ),
    ]
