# Generated by Django 4.0.7 on 2022-09-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, default='defaults/user.png', null=True, upload_to=''),
        ),
    ]
