# Generated by Django 4.0.7 on 2022-09-17 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0002_alter_userinfo_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
