# Generated by Django 4.0.7 on 2022-09-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0003_blockkeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blockkeyword',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
    ]
