# Generated by Django 4.0.7 on 2022-09-17 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nf_core', '0004_alter_blockkeyword_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRechargeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(blank=True, max_length=200, null=True)),
                ('trx_id', models.CharField(blank=True, max_length=200, null=True)),
                ('trx_type', models.CharField(blank=True, max_length=200, null=True)),
                ('recharge_amount', models.FloatField()),
                ('previous_balance', models.FloatField(blank=True, default=0, null=True)),
                ('new_balance', models.FloatField(blank=True, default=0, null=True)),
                ('balance_expiry_date', models.DateField(blank=True, null=True)),
                ('gw_response', models.TextField(blank=True, null=True)),
                ('trx_remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recharge_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Recharge History',
                'verbose_name_plural': 'User Recharge History',
            },
        ),
    ]
