# Generated by Django 4.0.7 on 2022-09-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0005_userrechargehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_group',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
