# Generated by Django 4.0.7 on 2022-09-18 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nf_core', '0006_userinfo_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('queue', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'SMS Route',
                'verbose_name_plural': 'SMS Route',
            },
        ),
        migrations.CreateModel(
            name='SMSType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSMSRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(max_length=200)),
                ('prefix', models.CharField(max_length=5)),
                ('masking_rate', models.FloatField()),
                ('non_masking_rate', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('queue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_queue', to='nf_core.smsqueue')),
                ('sender_id', models.ManyToManyField(blank=True, to='nf_core.senderid')),
                ('sms_rate', models.ManyToManyField(blank=True, to='nf_core.usersmsrate')),
                ('sms_type', models.ManyToManyField(blank=True, to='nf_core.smstype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Configuration',
                'verbose_name_plural': 'User Configuration',
            },
        ),
    ]
