# Generated by Django 4.0.7 on 2022-09-18 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0008_remove_userconfig_sms_type_smsqueue_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='priority',
            field=models.BooleanField(default=False),
        ),
    ]
