# Generated by Django 4.0.7 on 2022-09-23 10:24

from django.db import migrations, models
import nf_core.helper
import nf_core.models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0012_contacts_contacts_nf_core_con_user_id_f6bf58_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user_image',
            field=models.ImageField(blank=True, default='defaults/user.png', null=True, upload_to=nf_core.models.generate_filename),
        ),
    ]
