# Generated by Django 4.0.7 on 2022-09-23 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0014_auto_20220923_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrechargehistory',
            name='gw_response',
        ),
    ]
