# Generated by Django 4.0.7 on 2022-09-23 14:26

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0016_rename_trx_remarks_userrechargehistory_remarks_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userrechargehistory',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
