# Generated by Django 4.0.7 on 2022-09-23 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0017_alter_userrechargehistory_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='userrechargehistory',
            managers=[
            ],
        ),
    ]
