# Generated by Django 4.0.7 on 2022-09-23 14:27

from django.db import migrations
import psqlextra.manager.manager


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0018_alter_userrechargehistory_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrechargehistory',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='userrechargehistory',
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
    ]
