# Generated by Django 4.0.7 on 2022-09-23 14:28

from django.db import migrations
import psqlextra.backend.migrations.operations.delete_partitioned_model


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0019_alter_userrechargehistory_options_and_more'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.delete_partitioned_model.PostgresDeletePartitionedModel(
            name='RechargeHistory',
        ),
    ]
