# Generated by Django 4.0.7 on 2022-09-23 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0020_delete_rechargehistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRechargeHistory',
        ),
    ]
