# Generated by Django 4.0.7 on 2022-09-23 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import psqlextra.backend.migrations.operations.add_default_partition
import psqlextra.backend.migrations.operations.create_partitioned_model
import psqlextra.manager.manager
import psqlextra.models.partitioned
import psqlextra.types


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nf_core', '0022_auto_20220923_2036'),
    ]

    operations = [
        psqlextra.backend.migrations.operations.create_partitioned_model.PostgresCreatePartitionedModel(
            name='SMSHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shoot_id', models.CharField(blank=True, max_length=200, null=True)),
                ('receiver', models.CharField(max_length=200)),
                ('sender_id', models.CharField(blank=True, max_length=200, null=True)),
                ('operator_name', models.CharField(blank=True, max_length=200, null=True)),
                ('sms_type', models.CharField(max_length=200)),
                ('sms_length', models.IntegerField()),
                ('sms_count', models.IntegerField()),
                ('sms_body', models.TextField()),
                ('sms_body_encoded', models.TextField()),
                ('sms_rate', models.FloatField(default=0)),
                ('sms_cost', models.FloatField()),
                ('sms_status', models.BooleanField(default=False)),
                ('paused', models.BooleanField(default=False)),
                ('status', models.CharField(default='Pending', max_length=200)),
                ('scheduled', models.BooleanField(default=False)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sms_queue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='queue_sms_history', to='nf_core.smsqueue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_sms_history', to=settings.AUTH_USER_MODEL)),
            ],
            partitioning_options={
                'method': psqlextra.types.PostgresPartitioningMethod['RANGE'],
                'key': ['created_at'],
            },
            bases=(psqlextra.models.partitioned.PostgresPartitionedModel,),
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        psqlextra.backend.migrations.operations.add_default_partition.PostgresAddDefaultPartition(
            model_name='SMSHistory',
            name='default',
        ),
        migrations.AddIndex(
            model_name='smshistory',
            index=models.Index(fields=['user', 'receiver', 'sender_id', 'status'], name='nf_core_sms_user_id_5de1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='smshistory',
            index=models.Index(fields=['created_at'], name='nf_core_sms_created_7ce581_idx'),
        ),
    ]
