# Generated by Django 4.0.7 on 2022-09-23 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0023_auto_20220923_2039'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userrechargehistory',
            options={},
        ),
        migrations.RenameField(
            model_name='smshistory',
            old_name='scheduled_at',
            new_name='scheduled_time',
        ),
        migrations.AddField(
            model_name='smshistory',
            name='scheduled_params',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='userrechargehistory',
            index=models.Index(fields=['user', 'trx_id'], name='nf_core_use_user_id_bc1c75_idx'),
        ),
        migrations.AddIndex(
            model_name='userrechargehistory',
            index=models.Index(fields=['created_at'], name='nf_core_use_created_43f779_idx'),
        ),
    ]
