# Generated by Django 4.0.7 on 2022-09-24 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0027_remove_smshistory_paused_smshistory_sms_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='uid',
            field=models.CharField(default='ea9c1aea-6063-4c73-8daa-2498effd82ad', max_length=200),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='key',
            field=models.TextField(default='0c3ee641-ba76-4adf-aa07-b968e1211b1d'),
        ),
    ]
