# Generated by Django 4.0.7 on 2022-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0029_alter_smshistory_uid_alter_userloginsession_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smshistory',
            name='uid',
            field=models.CharField(default='cde4890c-6150-4f18-a964-069dafbfc4f8', max_length=200),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='key',
            field=models.TextField(default='89d9fe1c-9c29-4662-b3ca-0ea329dbcd87'),
        ),
    ]
