# Generated by Django 4.0.7 on 2022-09-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0030_alter_smshistory_uid_alter_userloginsession_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smshistory',
            name='uid',
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='key',
            field=models.TextField(default='5d70c75d-81ce-4478-a692-192e785f80bd'),
        ),
    ]
