# Generated by Django 4.0.7 on 2022-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0031_remove_smshistory_uid_alter_userloginsession_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='uid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='userloginsession',
            name='key',
            field=models.TextField(default='43c1ba25-4ded-4242-91f7-b1de084e2ed9'),
        ),
    ]
