# Generated by Django 4.0.7 on 2022-09-24 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0032_smshistory_uid_alter_userloginsession_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userloginsession',
            name='key',
        ),
    ]
