# Generated by Django 4.0.7 on 2022-09-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0033_remove_userloginsession_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloginsession',
            name='key',
            field=models.TextField(null=True),
        ),
    ]
