# Generated by Django 4.0.7 on 2022-09-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0035_smsqueuehandler'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsqueuehandler',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
