# Generated by Django 4.0.7 on 2022-09-24 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0036_smsqueuehandler_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smshistory',
            name='sms_status',
        ),
    ]
