# Generated by Django 4.0.7 on 2022-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0037_remove_smshistory_sms_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='failure_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
