# Generated by Django 4.0.7 on 2022-11-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0038_smshistory_failure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='smshistory',
            name='api_response',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
