# Generated by Django 4.0.7 on 2023-01-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0040_smsqueuehandler_operator_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
