# Generated by Django 4.0.7 on 2023-02-01 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_core', '0041_alter_userinfo_address_alter_userinfo_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.IntegerField()),
                ('sms_queue', models.CharField(max_length=200)),
                ('params', models.TextField(blank=True, null=True)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('executed', models.BooleanField(default=False)),
            ],
        ),
    ]
